version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-test phase started on `date`"
      - echo "Checking for package.json..."
      - |
        if [ -f package.json ]; then
          echo "Installing dependencies..."
          npm install
        else
          echo "No package.json found, skipping dependency installation"
        fi

  build:
    commands:
      - echo "Test phase started on `date`"
      - |
        if [ -f package.json ]; then
          echo "Running tests..."
          npm test || echo "No tests found, skipping..."
          echo "Running linting..."
          npm run lint || echo "No linting configured, skipping..."
        else
          echo "No package.json found, skipping tests"
        fi

  post_build:
    commands:
      - echo "Post-test phase completed on `date`"
      - echo "Test stage completed successfully"
